<?php

namespace AppBundle\Repository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function categorystats()
    {
        //for parent
        $q = $this->getEntityManager()->createQuery("select c.libelle as name , count(p.id) as y from AppBundle:Categorie c LEFT JOIN AppBundle:Projet p where  p.categorie=c GROUP BY  c.id  ");

        return $query = $q->getResult();


    }
}
