<?php

namespace AppBundle\Repository;

/**
 * FreelancerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreelancerRepository extends \Doctrine\ORM\EntityRepository
{
    public function freelancercount(){
        $q=$this->getEntityManager()->createQuery("select COUNT(a) from AppBundle:Freelancer a ");

        return $query=$q->execute();
    }
    public function bynote(){
        $q=$this->getEntityManager()
            ->createQuery("select a from AppBundle:Freelancer a  ")->setMaxResults(7);

        return $query=$q->execute();
    }
}
