<?php

namespace AppBundle\Repository;

/**
 * FreelancerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreelancerRepository extends \Doctrine\ORM\EntityRepository
{
    public function freelancercount(){
        $q=$this->getEntityManager()->createQuery("select COUNT(a) from AppBundle:Freelancer a ");

        return $query=$q->execute();
    }
    public function bynote(){
        $q=$this->getEntityManager()
            ->createQuery("select a from AppBundle:Freelancer a  ")->setMaxResults(7);

        return $query=$q->execute();
    }

    public function searchfr($kw){
        $rs=$this->getEntityManager()->createQuery("select  f from AppBundle:Freelancer f where (f.aboutme like :kw) or (f.nom like :kw) or (f.prenom like :kw) or (f.domaine like :kw)   ")
        ->setParameter("kw","%".$kw."%");
        return $rs->getResult();
    }
}
