<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends EntityRepository
{

    public function getinbox($id)
    {


        $q=$this->getEntityManager()->createQuery("SELECT m from AppBundle:Message m
         LEFT JOIN m.sender p where m.date in(select MAX(l.date) from AppBundle:Message l where l.sender=p AND m.receiver=l.receiver Group by l.sender) AND  m.receiver=:id   ORDER BY m.date DESC
            ")->setParameter('id',$id);

//        $q=$this->getEntityManager()->createQuery("select m from AppBundle:Message m  group by m.sender , m.receiver having m.sender =:id or m.receiver =:id order by m.date")->setParameter('id',$id);
        return $query=$q->getResult();


    }

    public function getmine($rec, $sen)
    {
        //for parent
        $q = $this->getEntityManager()->createQuery("SELECT m    from AppBundle:Message m 
 where (m.sender=:sen AND  m.receiver=:rec) OR (m.sender=:rec AND  m.receiver=:sen) ")->setParameter('sen', $sen)->setParameter('rec', $rec);

        return $query = $q->getResult();


    }

}
