<?php

namespace AppBundle\Repository;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function paiementstats()
    {
        //had to user native query to use monthname and month functions it does not exist in doctrine
        $q = $this->getEntityManager()->getConnection()->prepare("SELECT  monthname (datepaiment)  as name, SUM(montant) as y  FROM   paiement p  GROUP BY MONTH (datepaiment) ");

        $query = $q->execute();
        return $q->fetchAll();


    }

    public function paimentclient($id)
    {
        $q = $this->getEntityManager()->createQuery("select p from AppBundle:Paiement p LEFT JOIN p.postulation post 
LEFT JOIN post.project proj LEFT JOIN proj.client c where c=:id")->setParameter("id",$id);
        return $query=$q->getResult();


    }
    public function paimentfreelance($id)
    {
        $q = $this->getEntityManager()->createQuery("select p from AppBundle:Paiement p LEFT JOIN p.postulation post 
LEFT JOIN post.freelance fr  where fr=:id")->setParameter("id",$id);
        return $query=$q->getResult();


    }

}
