<?php

namespace AppBundle\Repository;

/**
 * PostulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulationRepository extends \Doctrine\ORM\EntityRepository
{
}
