<?php

namespace AppBundle\Repository;

/**
 * PostulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulationRepository extends \Doctrine\ORM\EntityRepository
{
    public function projectBidders($id){

        $q=$this->getEntityManager()->createQuery("select a from AppBundle:Postulation a
         where a.project=:project ")
            ->setParameter('project',$id);
        return $query=$q->getResult();


    }
    public function Mybids($id){

        $q=$this->getEntityManager()->createQuery("select a from AppBundle:Postulation a
         where a.freelance=:fr ")
            ->setParameter('fr',$id);
        return $query=$q->getResult();


    }
}
