projet:
    resource: "@ProjetBundle/Controller/"
    type:     annotation
    prefix:   /

app_categorie:
    resource: "@ProjetBundle/Controller/CategorieController.php"
    type:     annotation

app_client:
    resource: "@UserBundle/Controller/ClientController.php"
    type:     annotation

app_freelancer:
    resource: "@UserBundle/Controller/FreelancerController.php"
    type:     annotation

app_admin:
    resource: "@UserBundle/Controller/AdminController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"